# Generated by Django 4.0.2 on 2022-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDb',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'coin_db',
                'managed': False,
            },
        ),
    ]
